### ISSUE TITLE
Question: What are bookmarks?

### ISSUE THREAD

**Issue by wgevaert** [neo4j-php/neo4j-php-client#139]
When updating to version `2.7.0`, my application broke because `Contracts\FormatterInterface` was changed. Of course, I would love to have the newest version of this package, so I want to update my implementation of the interface to this new signature.

The change is that `FormatBoltResult` has a `BookmarkHolder $holder` and I do not know what to do with it. Can I just ignore it?

**Comment by stefanak-michal** [comment]
I will answer the question what are bookmarks.

Bookmarks are used when Neo4j is running in cluster (multiple instances). When you execute query (cluster choose one instance to run it) and immediatelly execute another query while the cluster decide to use different instance, you can hit a problem when data was not synchronized (yet) between instances in cluster. From outside it looks like the data from first query was not processed. Bookmark solve this problem because with bookmark you are refering to changes executed in first query.

You can imagine bookmarks as git commit hash, it's like referring to moment in history.

**Comment by stefanak-michal** [comment]
I checked the readme and code about Formatters and it seems is up to you if you use it. 

If you look at BasicFormatter the BookmarkHolder is not used.
https://github.com/neo4j-php/neo4j-php-client/blob/439a59282f9fcfc6799b24fe617bf1ebf716ccc0/src/Formatter/BasicFormatter.php#L59-L70

If you want to use it you can get some inspiration in OGMFormatter where is applied with finished callback.
https://github.com/neo4j-php/neo4j-php-client/blob/439a59282f9fcfc6799b24fe617bf1ebf716ccc0/src/Formatter/OGMFormatter.php#L78-L94

Propably @transistive will know more (because he is author) and you can wait for his answer. ;)

**Comment by wgevaert** [comment]
Thank you for your response, I now know what to do!

**Comment by transistive** [comment]
Good stuff! The Basic Formatter should also do something with the bookmarks. Looks like an oversight from my side! I'll create an issue

@wgevaert, I'm thinking about redesigning the formatters in the next major release, as the parameters are getting a bit out of control. I'll create an issue for it later this week, so you can join the discussion if you want
