### ISSUE TITLE
No write operations are allowed directly on this database issue

### ISSUE THREAD

**Issue by AhmedElmaghraby207** [neo4j-php/neo4j-php-client#150]
**Describe the bug**
No write operations are allowed directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER

My neo4j connection is 
```
try {
    return $client->writeTransaction(static function (TransactionInterface $tsx) use ($statement) {
        return $tsx->run($statement->getText());
    });
} catch (Exception $e) {
    \Sentry\captureMessage($e->getMessage());
    return $client->writeTransaction(static function (TransactionInterface $tsx) use ($statement) {
        return $tsx->run($statement->getText());
    });
}
```
package  : laudis/neo4j-php-client
version:  2.6.1

**Comment by AhmedElmaghraby207** [comment]
@transistive Pls have a look at this

**Comment by transistive** [comment]
Hi @AhmedElmaghraby207,

Thank you for reaching out! We actually have tests exactly like this, and they work, so it will be difficult for me to reproduce the bug on my end. Can you explain a little bit more about your neo4j setup? Hopefully I'll be able to check it easier that way.

In the meantime, I'll check if I can find a bug in the code without reproducing it, because it shouldn't happen. I'm still working on the connection pool update atm which is probably where this bug happens, so I might be able to find it that way.

Thanks!

**Comment by transistive** [comment]
Hello @AhmedElmaghraby207, any updates on this with version 2.8.0? I closed the issue for now but feel free to reopen it
