### ISSUE TITLE
Neo4j 5 support plans

### ISSUE THREAD

**Issue by Emptyfruit** [neo4j-php/neo4j-php-client#156]
Hi ) Is supporting neo4j 5 somewhere in nearest plans ? As i see https://github.com/neo4j-php/Bolt already supports it, but the version here is fixed to ^4.

**Comment by transistive** [comment]
Hello @Emptyfruit,

Thank you for reaching out! I have scheduled tomorrow afternoon to release the update! I am still working through the backlog.

I'll ping you once it is done.

Kind regards,

Ghlen

**Comment by Emptyfruit** [comment]
Upd. 
As i found out, neo4j 5 is supposed to work with bolt v4, so can we assume that most functionality will work as it is with Neo4j 5?

**Comment by transistive** [comment]
Yes, it will work out of the box. I am aware people have tried it already. It is mainly about extending new features. No breaking change has been reported yet.

**Comment by stefanak-michal** [comment]
There is one important issue which was fixed related to DateTime and DateTimeZoneId data types. TLDR it's about Daylight Saving Time. You can read more about it here https://neo4j.com/developer-blog/a-timely-update-to-the-bolt-protocol/

But you are good for now because neo4j 5.0 - 5.1 supports Bolt v4.4 without problem. https://www.neo4j.com/docs/bolt/current/bolt-compatibility/

**Comment by transistive** [comment]
Neo4j 5 is fully supported and tested now in version 3.0.0
