### ISSUE TITLE
Support Neo4j 3.5 removed

### ISSUE THREAD

**Issue by tim-hanssen** [neo4j-php/neo4j-php-client#187]
The readme file describes support for Neo4j 3.5. The used Bolt package also supports this. In version 3+ of the client support for Bolt V3 seems to be removed and that breaks the support for Neo4j 3 versions.

After updating to a client version 3+ a `Wrong version` error is thrown.

 - Library version: latest tag 3.0.5
 - Neo4j Version: 3.5.35
 - PHP version: PHP 8.2.10
 - OS: Mac OS latest

**Comment by transistive** [comment]
Hello Tim,

Version 3.5 is not supported by the driver in version 3.0 and up. Some of the more advanced features the driver uses now are not possible in this version. Furthermore, version 3.5 has been unsupported by Neo4j since May 27, 2022.

I have updated the readme accordingly.

Thank you for bringing this to my attention.

Kind regards,

Ghlen
