### ISSUE TITLE
Error when connect neo4j with PHP

### ISSUE THREAD

**Issue by NgMinhTri** [neo4j-php/neo4j-php-client#50]
Hi there
I have a problem when I connect Neo4j with PHP.  I have found the answer but 
very few people discuss it

- 

- 

> 

> 
![Screenshot (271)](https://user-images.githubusercontent.com/38482726/121809138-d61eee00-cc85-11eb-9715-d47e7d15bc40.png)

**Comment by transistive** [comment]
Hello @NgMinhTri,

Thank you for reaching out. This is because the underlying library for the bolt protocol enforces you to have ext-sockets installed. If you do not plan on using bolt but only HTTP you can ignore this requirement by using `composer install --ignore-platform-requirements`.

Best of luck,

Ghlen
